services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: titanic_backend
    ports:
      - "${API_PORT}:8000"
    depends_on:
      db:
        condition: service_healthy
      mlflow:
        condition: service_healthy
      trainer:
        condition: service_completed_successfully
    environment:
      - PYTHONUNBUFFERED=1
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    env_file:
      - .env
    volumes:
      - .:/app
    restart: always

  trainer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: titanic_trainer
    depends_on:
      db:
        condition: service_healthy
      mlflow:
        condition: service_healthy
    environment:
      - PYTHONUNBUFFERED=1
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    env_file:
      - .env
    volumes:
      - .:/app
    command: ["python", "train.py"]
    restart: "no"


  mlflow:
    container_name: titanic_mlflow
    image: python:3.10-slim
    ports:
      - "${MLFLOW_PORT}:5000"
    environment:
      - MLFLOW_DB=${MLFLOW_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./mlruns:/data/mlruns
      - ./mlflow.db:/data/mlflow.db
      - ./start_mlflow.sh:/app/start_mlflow.sh
    command: ["sh", "/app/start_mlflow.sh"]
    healthcheck:
      test: ["CMD-SHELL", "python -c 'import urllib.request; urllib.request.urlopen(\"http://localhost:5000/health\")' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 30s
    restart: always

  db:
    container_name: titanic_postgres
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - titanic_db:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    restart: always

volumes:
  titanic_db: